---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Installs packages
      yum: 
        pkg: ['vim', 'git', 'tmux', 'tree', 'zsh', 'wget']
        state: latest
