---
- hosts: paperless
  become: true
  tasks:
    - name: Installs packages
      dnf: pkg={{ item }} state=latest 
      with_items:
        - vim
        - htop
        - git
        - tmux
        - tree
        - zsh
        - wget
        - python3
        - gnupg
        - tesseract
        - unpaper
        - poppler
        - ImageMagick
